
services:

  nginx-primary:
    image: bhartford419/nginx-certbot:alpine
    environment:
      - DOMAIN=stg.serverless-nostr.com
      - DOCKER_SVC=primary_websocket_handler
      - SVC_PORT=8008
      - VERSION=1.0.0
      - CONTACT=bh419@protonmail.com
      - HEX_PUBKEY=4503baa127bdfd0b054384dc5ba82cb0e2a8367cbdb0629179f00db1a34caacc
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - swarm-overlay-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.region == useast


networks:
  swarm-overlay-network:
    driver: overlay
    attachable: true
    external: true



