
services:
  secondary_websocket_handler:
    image: bhartford419/nostpy-ws-handler:latest
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - EVENT_HANDLER_SVC=secondary_event_handler
      - EVENT_HANDLER_PORT=8010
      - WS_PORT=8007
    ports:
      - target: 8007
        published: 8007
        protocol: tcp
        mode: ingress
    networks:
      - swarm-overlay-network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.region == eucentral

  secondary_event_handler:
    image: bhartford419/nostpy-eh-handler:latest
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - REDIS_HOST=redis-secondary
      - EVENT_HANDLER_PORT=8010
      - REDIS_PORT=6740
      - PGDATABASE_WRITE=postgres
      - PGUSER_WRITE=postgres
      - PGPASSWORD_WRITE=postgres
      - PGPORT_WRITE=5432
      - PGHOST_WRITE=postgres-primary
      - PGDATABASE_READ=postgres
      - PGUSER_READ=postgres
      - PGPASSWORD_READ=postgres
      - PGPORT_READ=5433
      - PGHOST_READ=postgres-secondary
    networks:
      - swarm-overlay-network

    ports:
      - target: 8010
        published: 8010
        protocol: tcp
        mode: ingress

    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.region == eucentral

  redis-secondary:
    image: redis:latest
    ports:
      - target: 6340
        published: 6340
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.region == eucentral
    networks:
      - swarm-overlay-network


networks:
  swarm-overlay-network:
    driver: overlay
    attachable: true
    external: true
