
services:
  primary_websocket_handler:
    image: bhartford419/nostpy-ws-handler:latest
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - EVENT_HANDLER_SVC=primary_event_handler
    ports:
      - target: 8008
        published: 8008
        protocol: tcp
        mode: ingress
    networks:
      - swarm-overlay-network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.region == useast

  primary_event_handler:
    image: bhartford419/nostpy-eh-handler:latest
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - REDIS_HOST=redis
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGHOST=172.31.38.172
    networks:
      - swarm-overlay-network

    ports:
      - target: 8009
        published: 8009
        protocol: tcp
        mode: ingress

    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.region == useast

  redis-primary:
    image: redis:latest
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.region == useast
    networks:
      - swarm-overlay-network


networks:
  swarm-overlay-network:
    driver: overlay
    attachable: true
    external: true
