services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug
    ports:
      - "55680:55680"
      - "4317:4317"
      - "4318:4318"
    configs:
      - source: opentelemetry-config
        target: /etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 350M
        reservations:
          cpus: '0.25'
          memory: 250M
    networks:
      - swarm-overlay-network


configs:
  opentelemetry-config:
    external: true
