services:

  nginx-secondary:
    image: bhartford419/nginx-certbot:alpine
    environment:
      - DOMAIN=stg.serverless-nostr.com
      - DOCKER_SVC=primary_websocket_handler
      - SVC_PORT=8008
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - swarm-overlay-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.region == eucentral


networks:
  swarm-overlay-network:
    driver: overlay
    attachable: true
    external: true

#volumes:
#  certs:
#    external: true
#  certs-data:
#    external: true

